apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
  namespace: system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: heat
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: heat-role
  namespace: openstack
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - anyuid
    resources:
      - securitycontextconstraints
    verbs:
      - use
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - get
      - list
      - patch
      - post
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: heat-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: heat-role
subjects:
  # Applying the role to both SA (with and without prefix) to be able
  # to run the operator local
  - kind: ServiceAccount
    name: heat-operator-heat
    namespace: openstack
  - kind: ServiceAccount
    name: heat
    namespace: openstack
