apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: heats.heat.openstack.org
spec:
  group: heat.openstack.org
  names:
    kind: Heat
    listKind: HeatList
    plural: heats
    singular: heat
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Heat is the Schema for the heats API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: HeatSpec defines the desired state of Heat
          properties:
            databaseAdminPassword:
              type: string
            databaseAdminUsername:
              type: string
            heatAPIContainerImage:
              type: string
            heatAPIReplicas:
              format: int32
              type: integer
            heatDatabasePassword:
              type: string
            heatDatabaseUsername:
              type: string
            heatEngineContainerImage:
              type: string
            heatEngineReplicas:
              format: int32
              type: integer
            heatMessagingPassword:
              type: string
            heatMessagingUsername:
              type: string
            heatServicePassword:
              type: string
            heatStackDomainAdminPassword:
              type: string
            mysqlContainerImage:
              type: string
          required:
          - heatAPIReplicas
          - heatEngineReplicas
          - heatServicePassword
          - heatStackDomainAdminPassword
          type: object
        status:
          description: HeatStatus defines the observed state of Heat
          properties:
            dbSyncHash:
              description: DbSync hash
              type: string
            deploymentHash:
              description: Deployment hash used to detect changes
              type: string
            engineDeploymentHash:
              type: string
          required:
          - dbSyncHash
          - deploymentHash
          - engineDeploymentHash
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
