apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: "[]"
    capabilities: Basic Install
  name: heat-operator.v0.0.1
  namespace: openstack
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: heat is the Schema for the heats API
        displayName: heat
        kind: Heat
        name: heats.heat.openstack.org
        version: v1alpha1
      - description: Heat is the Schema for the heats API
        displayName: Heat
        kind: Heat
        name: heats.heat.openstack.org
        version: v1beta1
  description: heat operator
  displayName: heat-operator-bundle
  icon:
    - base64data: ""
      mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  keywords:
    - OpenStack
    - Orchestration
    - Heat
  links:
  - name: Heat Operator
    url: https://github.com/openstack-k8s-operators/heat-operator
  maturity: alpha
  provider:
    name: Red Hat Inc.
    url: https://redhat.com/
  version: 0.0.0
