apiVersion: apps/v1
kind: Deployment
metadata:
  name: heat-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: heat-operator
  template:
    metadata:
      labels:
        name: heat-operator
    spec:
      serviceAccountName: heat-operator
      containers:
        - name: heat-operator
          image: quay.io/openstack-k8s-operators/heat-operator:devel
          command:
          - heat-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "heat-operator"
