kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: heat-operator
subjects:
- kind: ServiceAccount
  name: heat-operator
roleRef:
  kind: Role
  name: heat-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: heat
subjects:
- kind: ServiceAccount
  name: heat
roleRef:
  kind: Role
  name: heat
  apiGroup: rbac.authorization.k8s.io
