apiVersion: heat.openstack.org/v1beta1
kind: Heat
metadata:
  name: heat
spec:
  customServiceConfig: "# add your customization here"
  databaseInstance: openstack
  databaseUser: "heat"
  debug:
    bootstrap: false
    dbSync:
    service: false
  heatAPI:
    containerImage: "quay.io/tripleozedcentos9/openstack-heat-api:current-tripleo"
    customServiceConfig: "# add your customization here"
    databaseUser: "heat"
    debug:
      bootstrap: false
      dbSync: false
      service: false
    passwordSelectors:
      admin: AdminPassword
      database: AdminPassword
    replicas: 1
    resources: {}
    secret: "osp-secret"
    serviceUser: ""
  heatEngine:
    containerImage: "quay.io/tripleozedcentos9/openstack-heat-engine:current-tripleo"
    customServiceConfig: "# add your customization here"
    databaseUser: "heat"
    debug:
      bootstrap: false
      dbSync: false
      service: false
    passwordSelectors:
      admin: AdminPassword
      database: AdminPassword
    replicas: 1
    resources: {}
    secret: "osp-secret"
    serviceUser: ""
  passwordSelectors:
    admin: AdminPassword
    database: AdminPassword
  preserveJobs: false
  secret: osp-secret
  serviceUser: "heat"
